
TIME_FMT = "%Y-%m-%d"

DATASOURCE_ALPACA = 'alpaca'
DATASOURCE_CACHE = 'cache'
FREQ_DAY = 'day'
FREQ_MINUTE = 'minute'

VALID_DATASOURCE = [DATASOURCE_ALPACA, DATASOURCE_CACHE]
VALID_FREQ = [FREQ_DAY, FREQ_MINUTE]

DATA_FILE_FMT = "{symbol}_{freq}_{start_date}_{end_date}"

DATA_KEY_DF = "df"
DATA_KEY_PATH = "path"
